### ISSUE TITLE
config.ymlのbooknameをbook以外にすると変更が効かなくなる

### ISSUE THREAD

**Issue by aiya000** [at-grandpa/review-and-css-typesetting#13]
こんにちは！
最高のプロダクトをありがとうございます！
技術書典9に向けて、使わせていただいております。

問題はタイトルの通りなのですが、
config.ymlの`bookname`をbook以外にすると、
他のconfig.ymlや\*.reへの変更が、.pdfに現れなくなります。

もし再現が必要でしたら、僕が活動を行っているprivateリポジトリへinviteいたします。

`problematic~`は問題が「変更が正しく反映される」リビジョンで、
`problematic`が「変更が反映されない」リビジョンです。

よろしくお願いいたします！

**Comment by at-grandpa** [comment]
@aiya000 
ご報告ありがとうございます！

手元で `bookname` を変更してみたところ、ちょっと再現できなかったので、inviteよろしいでしょうか？

お手数ですが、よろしくおねがいします 🙇

**Comment by aiya000** [comment]
@at-grandpa 招待させていただきました🙇

problematicブランチに移動していただいて、そのリビジョンの一つ前が問題なくビルドできる環境で、problematicブランチのちょうどそのリビジョンが問題の出る環境です🙏

**Comment by at-grandpa** [comment]
@aiya000 

inviteありがとうございます！
原因がわかりました。

https://github.com/at-grandpa/review-and-css-typesetting/blob/master/in_docker.mk#L41
このコマンドをdockerの中で叩いているのですが、この際、`review-epubmaker config.yml`のコマンドの時点で「config.ymlの`bookname`をファイル名に用いたepubファイル」が出力されます。

しかし、次のコマンド `review-epub2html book.epub` では `book.epub` を引数に取っています。この `book.epub` は「config.ymlの`bookname`がデフォルトの`book`のときに生成されたもの」です。

つまり、`bookname`を変更した直後から、

* 最新の変更は「config.ymlの`bookname`をファイル名に用いたepubファイル」に出力されている
* html変換の際には `book.epub` を見ている（もちろん最新の変更はナシ）

となっていました。過去に生成された `book.epub` をずっと見ていたことになります。

 これはバグです。ご指摘ありがとうございます！

ちょっと修正にお時間をいただいてしまうかもしれません。
もし直近で対応されたい場合は、config.ymlの`bookname`を `book`に戻していただくことになりそうです。。
（生成やcssの反映に `book` という文字が結構依存しており。。。）

お手数おかけしてすみません 🙇

**Comment by aiya000** [comment]
今回は「book」のままいっても支障がないように思えるので、時間がかかってしまっても全然大丈夫です👍️

素晴らしいプロダクトを、ありがとうございます！

**Comment by at-grandpa** [comment]
いえいえ！こうやって「使っていただいている方からのフィードバック」はとても嬉しいので、また何かありましたらご連絡ください。

改めて、ご指摘ありがとうございました！

**Comment by at-grandpa** [comment]
@aiya000 
招待して頂いたprivateリポジトリですが、共有解除していただいて結構ですー 👍 
ご丁寧にありがとうございました 🙏
